### ISSUE TITLE
Add more detail on npm scripts

### ISSUE THREAD

**Issue by gavinorland** [survivejs/maintenance-book#12]
In packaging/anatomy it would be good to see more information about npm scripts. For example, the way that `start`, `stop` and `test` are shortcuts included which can be triggered without using `run` whereas others must be preceded with `run`. And the way that you can prefix any script with 'pre' or 'post' so that it's run before or after its main script. And whether there are any special implications to the `main:sub` syntax.

**Comment by bebraw** [comment]
Done. Added more info on the above topics.
