### ISSUE TITLE
Documentation - API

### ISSUE THREAD

**Issue by rstegg** [survivejs/maintenance-book#2]
I like to use Most.js as an example of a complete API: https://github.com/cujojs/most/blob/master/docs/api.md

API documentation might cover:

- [ ] Being one of the necessary documentation styles when having a modular codebase
- [ ] Helping your users learn your code faster & being "developer friendly"
- [ ] Massive code-bases such as [stripe](https://stripe.com/docs) (also a great API)
- [ ] tools for auto-generating API such as [swagger](http://swagger.io/) (never used)
- [ ] "OpenAPI" [specification](https://www.openapis.org/specification/repo)

- Pros: 
  - A bag of goodies; 
  - everything you need is clicks away; 
  - promotes growth to the library

- Cons: 
  - Maintaining a separate piece of your codebase can mean possibly double the amount of work to add/remove a feature; 
  - the time it takes is obnoxious; 
  - larger-scale projects might find trouble in agreeing in API; 
  - "API" can be an ambiguous term (see: google vs oracle 😄 )

**Comment by bebraw** [comment]
@sapegin Something for the documentation part of the book. Maybe doing pros/cons for different approaches is the way to go.

**Comment by sapegin** [comment]
I think we have enough for now about APIs.

**Comment by bebraw** [comment]
Ok, time to close.

@rstegg Please review and open more issues as you notice things.
