### ISSUE TITLE
Discuss GitHub teams?

### ISSUE THREAD

**Issue by bebraw** [survivejs/maintenance-book#29]
This is related to the process topic and it becomes important as a project grows.

**Comment by gavinorland** [comment]
I think this is relevant - maybe even discussing forking, and Github Pages etc. too. Not every aspect of using Git but just how to collaborate. There are a few things I've learned, like having my "origin" of a local repo point to my fork but my "upstream" pointing to the original - things like that - workflow stuff.

**Comment by bebraw** [comment]
Yeah, something for the process chapter. I think we have GitHub Pages covered elsewhere.

**Comment by gavinorland** [comment]
Yes, I see you do discuss forks briefly already too. Could be scope for some more procedural tips in the future.
