### ISSUE TITLE
Discovering Explicit vs Implicit trade-offs

### ISSUE THREAD

**Issue by rstegg** [survivejs/maintenance-book#3]
To discover the trade-offs for Explicit and Implicit code, a "DIY" build system might be useful [but probably not]. 

- [ ] Bash scripts
- [ ] Rollup.js
- [ ] Webpack/2
- [ ] npm scripts
- [ ] grunt? gulp? others?

- pros/cons of having a robust vs minimal build system?
- when introducing a build system might deem valid?
- picking the "right tool for the job"

**Comment by bebraw** [comment]
I'm still thinking about this. I think I solved this implicitly. Now we discuss npm scripts first and rollup/webpack later. The current status feels enough. Please open specific issues related to the current content as you go through the content.
