### ISSUE TITLE
Publishing types

### ISSUE THREAD

**Issue by bebraw** [survivejs/maintenance-book#40]
> Publishing types should be a separate chapter. You don’t have to use Flow/TS yourself to publish typings.

**Comment by bebraw** [comment]
Maybe it would be enough to have this as a tip or a small section in the current typing chapter even and refer to the following:

* https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
* https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4

**Comment by bebraw** [comment]
Interesting point

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

So it's convention based.

**Comment by bebraw** [comment]
I also have to figure out the correct way to do this for Flow. Also, what if you want both? Likely you have to choose one.

**Comment by sapegin** [comment]
I actually think that publishing types is more in the scope of the book than comparing typing systems.
