### ISSUE TITLE
Figure out a better subtitle

### ISSUE THREAD

**Issue by bebraw** [survivejs/maintenance-book#50]
The current one feels too vague and doesn’t reflect the content accurately. I think we might need something more concrete here.

**Comment by gavinorland** [comment]
Instead of "Maintenance - From Apprentice to Master"?

Maybe "Maintenance - Optimising Front-End Workflow".

**Comment by bebraw** [comment]
That's a good try! It's not only about front-end, though. Maybe we can move from that a bit. "Maintenance - Optimize Your JavaScript Workflow" (american spelling 🥇 ).

We also thought about variants like "Tame your JavaScript projects" and “How to keep your sanity maintaining open source library”.

**Comment by gavinorland** [comment]
> Maintenance - Optimize Your JavaScript Workflow

I that :) Or "Maintenance - Optimizing JavaScript Workflow"...

**Comment by sapegin** [comment]
“Streamlining JavaScript Workflow”. Optimizing may feel like we’re going to teach performance. A [good example](https://www.amazon.com/Lightroom-Streamlining-Digital-Photography-Process/dp/1118645219) from another area.

**Comment by bebraw** [comment]
Yeah, streamlining sounds much better.

**Comment by gavinorland** [comment]
I like "streamlining" (and of course all of this is up to you guys) - the word just sounds to me a bit like the user already knows all this stuff but you're just going to organise what they know a bit better. With "optimising" it's like they might be doing everything manually but you're going to show them all the things that can automate it!

These are very subtle things though, and that's a sound point that "optimising" has a specific meaning in computing (namely speed) - so streamlining sounds good!

**Comment by bebraw** [comment]
> some keywords that do pop in my head are 'organising your JS' and 'professionally'

Ideas from a friend.
