### ISSUE TITLE
eslintrc do not support json5

### ISSUE THREAD

**Issue by Aladdin-ADD** [survivejs/maintenance-book#88]
https://github.com/survivejs/maintenance-book/blob/master/manuscript/code-quality/01-linting.md#eslint-configuration-formats

`.eslintrc` support some json5 features.(like single-quoted string, unquoted object keys).  but it has been deprecated (https://eslint.org/docs/user-guide/configuring#configuration-file-formats)

**Comment by sapegin** [comment]
Yup, we should update it to `.eslintrc.json`.
